# Generated by Django 3.2 on 2024-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='user',
        ),
        migrations.AddField(
            model_name='registry',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='first_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='last_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='phone_number',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
